# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendzone_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='met_date',
            field=models.DateField(verbose_name='date met'),
        ),
    ]
