# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendzone_ui', '0002_auto_20170520_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='conduit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conduit', to='friendzone_ui.Friend'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
